# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UbswGHkkEE72I7EHPaQdXjMmaIy9TWJK
"""

a, b = map(int, input().split())
if(b-a == 1 or b-a == 2):
  print("B")
else:
  print("A")