# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UbswGHkkEE72I7EHPaQdXjMmaIy9TWJK
"""

t = int(input())
for i in range(1, t + 1) :
    n = int(input())
    result = ''
    for j in range(n) :
        al, count = input().split()
        result += al * int(count)

    num = 0
    print('#%d' % i)
    for j in range(len(result)) :
        print(result[j], end='')
        num += 1
        if num == 10 :
            num = 0
            print()