# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UbswGHkkEE72I7EHPaQdXjMmaIy9TWJK
"""

A= int(input())
B= A//1000
C= A//100 -10*B
D= A//10 - 100*B - 10*C
E = A%10
print(B+C+D+E)