# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UbswGHkkEE72I7EHPaQdXjMmaIy9TWJK
"""

A = int(input())
B = list(map(int, input().split()))
A = int((A-1)/2)
B.sort()
print(B[A])

