# -*- coding: utf-8 -*-
"""6003

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1adqLgcvVlJgQkTVveZL4h_fItrHjz4pl
"""

print('Hello\nWorld')

