# -*- coding: utf-8 -*-
"""6010

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1adqLgcvVlJgQkTVveZL4h_fItrHjz4pl
"""

n = input()
print(int(n))

