# -*- coding: utf-8 -*-
"""6011

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1adqLgcvVlJgQkTVveZL4h_fItrHjz4pl
"""

A = input()
print(float(A))

